[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  framework = "#custom"

[[edge_functions]]
  path = "/github-auth"
  function = "github-auth"

[[edge_functions]]
  path = "/cors-proxy/*"
  function = "cors-proxy"
