[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  # TODO: Find a better way to handle this in different environments
  VITE_CORS_PROXY = "https://numen.netlify.app/cors-proxy"

[[edge_functions]]
  path = "/github-auth"
  function = "github-auth"

[[edge_functions]]
  path = "/cors-proxy/*"
  function = "cors-proxy"
