[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  # Use Netlify's URL environment variable to make it environment-agnostic
  VITE_CORS_PROXY = "${URL}/cors-proxy"

[[edge_functions]]
  path = "/github-auth"
  function = "github-auth"

[[edge_functions]]
  path = "/cors-proxy/*"
  function = "cors-proxy"
