name: Lumen
on:
  workflow_call:
    inputs:
      notes:
        type: string
        description: "Glob pattern to match note files. All note files must be markdown files."
        required: false
        default: "**/*.md"
# Cancel running workflow when a new workflow is triggered on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lumen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build notes.json
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Create an empty object to store the notes
            const notes = {};

            const globber = await glob.create('${{ inputs.notes }}')
            const files = await globber.glob()

            // Iterate through all the notes
            files
              // Ignore non-markdown files
              .filter((filename) => filename.endsWith('.md'))
              .forEach((filename) => {

                // Relative path
                const relativePath = path.relative(process.cwd(), filename);

                // Remove the .md extension from the filename
                const id = relativePath.replace(/\.md$/, '');
                
                // Read the body of the note
                const body = fs.readFileSync(filename, 'utf8');

                // Add the note to the notes object
                notes[id] = body;
              });

            // Create the .lumen directory if it doesn't exist
            if (!fs.existsSync('.lumen')) {
              fs.mkdirSync('.lumen');
            }

            // Write the output to a .json file
            fs.writeFileSync('.lumen/notes.json', JSON.stringify(notes));
      - name: Commit notes.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build notes.json"
